name: iOS starter workflow

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    name: Build and Test iOS App
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set Up CocoaPods
        run: |
          gem install cocoapods
          pod install --repo-update

      - name: Build
        run: |
          xcodebuild build-for-testing -workspace GitUser.xcworkspace \
          -scheme Domain \
          -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5"

      - name: Test
        run: |
          for scheme in "GitUser" "Data" "Domain"; do
            echo "Running tests for scheme: $scheme"
            xcodebuild test-without-building -workspace GitUser.xcworkspace \
            -scheme "$scheme" \
            -destination "platform=iOS Simulator,name=iPhone 15,OS=17.5" || exit 1
          done
